# configure worker name and Cloudflare account
name = "assetsDashboard"
account_id = "852dfa4ae1b0d579df29be65b986c101"

# TODO: when hosting the domain on cloudflare:
# 1. disable workers_dev (except for development)
workers_dev = true
# 2. add routes to worker
# route = "assets.coke.com/*"
# 3. disable preview_urls and replace with a separate
#    route preview.assets.coke.com/* that effectively
#    uses *.aem.page as origin (likely needs a code change)
preview_urls = true


# do not change these unless code changes require it
main = "src/index.js"
compatibility_date = "2025-08-16"


# TODO: disable logs when development is done
[observability.logs]
enabled = true


[vars]
# Configure origins here
HELIX_ORIGIN = "https://main--assetsDashboard--aemsites.aem.live"
DM_ORIGIN = "https://delivery-p64403-e544653.adobeaemcloud.com"
FADEL_ORIGIN = "https://test.fadelarc.net"

# keep disabled as long as we are using workers.dev directly without a domain/zone
HELIX_PUSH_INVALIDATION = "disabled"

# Microsoft Entra IDP (config)
MICROSOFT_ENTRA_TENANT_ID = "801ee00e-24ef-45c3-848b-b88400248100"
MICROSOFT_ENTRA_CLIENT_ID = "0738fc65-4925-42f3-9a18-2080c3ebfa96"
MICROSOFT_ENTRA_JWKS_URL = "https://login.microsoftonline.com/common/discovery/keys"

SESSION_COOKIE_EXPIRATION = "6h"
LOGIN_PAGE = "/public/welcome"

# Secrets
[[secrets_store_secrets]]
store_id = "5d64b0d295964846b36569f507fb7b13"
binding = "COOKIE_SECRET"
secret_name = "assetsDashboard_COOKIE_SECRET"

[[secrets_store_secrets]]
store_id = "5d64b0d295964846b36569f507fb7b13"
binding = "DM_CLIENT_ID"
secret_name = "assetsDashboard_DM_CLIENT_ID"

[[secrets_store_secrets]]
store_id = "5d64b0d295964846b36569f507fb7b13"
binding = "DM_CLIENT_SECRET"
secret_name = "assetsDashboard_DM_CLIENT_SECRET"

[[secrets_store_secrets]]
store_id = "5d64b0d295964846b36569f507fb7b13"
binding = "FADEL_USER"
secret_name = "assetsDashboard_FADEL_USER"

[[secrets_store_secrets]]
store_id = "5d64b0d295964846b36569f507fb7b13"
binding = "FADEL_PASSWORD"
secret_name = "assetsDashboard_FADEL_PASSWORD"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "975809e56a7a425aa006e156671bbecf"